### ISSUE TITLE
Get datetime in metadata into standard format

### ISSUE THREAD

**Issue by mattbellis** [mattbellis/hepfile#2]
When we store the metadata, we should see if there is some sort of standard format for saving dates as strings. For example, we should have the timezone in there. 

Maybe this post will help us? 

https://stackoverflow.com/questions/2150739/iso-time-iso-8601-in-python

**Comment by mattdreyer** [comment]
changed into ISO 8601 format, i *think* that's the default? we could maybe give the user the option of changing the date format if they really want

**Comment by mattdreyer** [comment]
not sure if it has timezone info in it though

**Comment by mattbellis** [comment]
Ah, I see. I didn't think this through. It gives the time as UTC. For instance, it's 4:20pm here. And I just did this.

```
In [1]: import datetime

In [2]: datetime.datetime.utcnow().isoformat()
Out[2]: '2021-07-09T20:20:06.640123'
```
I didn't fully appreciate the `utcnow().isoformat()` so I think we're all set!

https://en.wikipedia.org/wiki/Coordinated_Universal_Time

If people want to add a timezone to the metadata, they can do that themselves! :)

**Comment by mattbellis** [comment]
Nice job on this!
