### ISSUE TITLE
Add example notebook with how to add header information to a hepfile

### ISSUE THREAD

**Issue by noahfranz13** [mattbellis/hepfile#61]

**Comment by mattbellis** [comment]
I added the code to `write.py` and `read.py` and added an example notebook in `sandbox`. Check it out and let me know what you think @noahfranz13 . We can iterate on it before we pull to main. 

I added a new error to `error.py` in line with your approach.

**Comment by noahfranz13** [comment]
I like how you did this! It appears very flexible to support headers from different datatypes we may want to store in hepfiles. I added a `print_file_header` function to `read.py` since we have the same type of function with the metadata. I think once we address issue #68 we are good to merge this functionality over!
