### ISSUE TITLE
Issue with writing string datasets with `dtype="S256"`

### ISSUE THREAD

**Issue by noahfranz13** [mattbellis/hepfile#76]
While working on creating a method for converting fits files to a hepfile (https://github.com/mattbellis/hepfile/blob/dev/sandbox/fits-tutorial-dev.ipynb) I've discovered that if the singletons name string conversion (conversion done here: https://github.com/mattbellis/hepfile/blob/86dcc405d92210ca1b944e0601d3c44ea553661f/src/hepfile/write.py#L456) exceeds 256 characters then setting `dtype="S256"` when creating an h5py dataset (https://github.com/mattbellis/hepfile/blob/86dcc405d92210ca1b944e0601d3c44ea553661f/src/hepfile/write.py#L675) cuts out any characters in the string that are part of the string exceeding 256 characters. 

As you can imagine, this causes serious issues when calling `hf.load` because it reads in any singleton data that has been cut out of the singleton name string as groups with no datasets, not singletons! 

@mattbellis Any ideas for this?

**Comment by noahfranz13** [comment]
Actually, I think I fixed this with the above commit and pull request! 

My fixes are in the following code chunk from `write.py`: https://github.com/mattbellis/hepfile/blob/a4b59c471f6427962de3a9fa5519ff766ec21857/src/hepfile/write.py#L665-L688

Essentially I changed the private methods that convert dictionaries and lists to strings for writing hdf5 files to also return the maximum length of the strings. This allows us to make sure we are writing the entire string to the hepfile instead of just 256 characters of it!

@mattbellis Let me know what you think and feel free to close this comment once you approve of this!

**Comment by mattbellis** [comment]
Oh wow, clever! I think this is great, but we should run some simple timing tests for both the writing _and _ the reading of these. If it all looks good, then yeah, let's merge it!

**Comment by noahfranz13** [comment]
I reran the timing tests from https://github.com/mattbellis/hepfile/blob/dev/sandbox/play_with_fastq.ipynb and compared the results to the results reported in Issues #57 and #58. I found the following results:

Method Call | Before Change Time (s) | After Change Time (s) |
|-------------|------------------|----------------|
| create_dataset, create_group, write_to_file | 3.722 | 3.925 |
| load | 53 | 61 |

I'm thinking this could also be because I pack the fastq files really inefficiently for hdf5 in this notebook. So, I tried again with a simpler case by copying over the [write_from_scratch.ipynb](https://github.com/mattbellis/hepfile/blob/dev/docs/example_nb/write_hepfiles_from_scratch.ipynb) notebook to sandbox and added some timing information to it. Here are the results of that:

Method Call | Before Change Time (s) | After Change Time (s) |
|-------------|------------------|----------------|
| create_dataset, create_group, write_to_file | 2.30 | 2.17 |
| load | 0.078 | 0.083 |

Once again, the write time difference seems negligible while the load time is slightly higher. I would argue that this slight increase in load time is worth it to get the advantage of being able to store any number of singletons rather than just 256 characters worth! What do you think?

**Comment by mattbellis** [comment]
I think this is a great test. I'm going to play with the `fastq` stuff later this week, but the fact that this implementation introduces minimal change is great. 

So in these tests, do you know how often the string is > 256 in length?

**Comment by noahfranz13** [comment]
Here are the results from testing with enough singletons to exceed the 256 character maximum we had set before:

| Command/Method Call | Before Change | After Change |
|---------------------------|------------------|----------------|
| create_dataset, create_group, write_to_file | 2.26 s | 2.15 s |
| load | 0.105 s | 0.091 s |
| `data['_SINGLETONS_GROUP_']` Output | Output (1) Below | Output (2) Below |

Output (1):
```
array(['METpx', 'METpy', 'test0', 'test1', 'test2', 'test3', 'test4',
       'test5', 'test6', 'test7', 'test8', 'test9', 'test10', 'test11',
       'test12', 'test13', 'test14', 'test15', 'test16', 'test17',
       'test18', 'test19', 'test20', 'tes'], dtype='<U6')
```

Output (2):
```
array(['METpx', 'METpy', 'test0', 'test1', 'test2', 'test3', 'test4',
       'test5', 'test6', 'test7', 'test8', 'test9', 'test10', 'test11',
       'test12', 'test13', 'test14', 'test15', 'test16', 'test17',
       'test18', 'test19', 'test20', 'test21', 'test22', 'test23',
       'test24', 'test25', 'test26', 'test27', 'test28', 'test29',
       'test30', 'test31', 'test32', 'test33', 'test34', 'test35',
       'test36', 'test37', 'test38', 'test39', 'test40', 'test41',
       'test42', 'test43', 'test44', 'test45', 'test46', 'test47',
       'test48', 'test49', 'test50', 'test51', 'test52', 'test53',
       'test54', 'test55', 'test56', 'test57', 'test58', 'test59',
       'test60', 'test61', 'test62', 'test63', 'test64', 'test65',
       'test66', 'test67', 'test68', 'test69', 'test70', 'test71',
       'test72', 'test73', 'test74'], dtype='<U6')
```

It looks like the time barely changed at all with a larger number of singletons (so the total number of characters exceeds 256). But, in the outputs, you can see the bug very clearly in how Output (1) gets cut off halfway through the test21 singleton! Any other concerns before we close this issue?

**Comment by mattbellis** [comment]
Oh, interesting. This looks great.

I do want to make sure I understand a few things more clearly. Can we discuss this when we meet tomorrow (Thur) before we fully close the issue?
