### ISSUE TITLE
"Protect" certain names of datasets

### ISSUE THREAD

**Issue by mattbellis** [mattbellis/hepfile#9]
For example, a user should not be allowed to create a `_DATASETS_AND_DICTIONARIES_` group, because we need that and we need it to be formatted in a particular way.

**Comment by mattbellis** [comment]
Need to be checked....

**Comment by noahfranz13** [comment]
This was done by introducing checks to `hepfile.write` to ensure group names and dataset names are not in the `hepfile.constants.protected_names` set.
